"""ZCode plugin for Dispatch — `dispatch zcode-plugin install|status|remove`.

ZCode (the OpenCode-based desktop app) reads the same plugin layout as Claude Code: a manifest,
`hooks/hooks.json`, `skills/`, `.mcp.json`. It runs SessionStart hooks and folds their
`hookSpecificOutput.additionalContext` into the session, exactly like Claude Code — that is the
one thing ZCode was missing to know it lives inside Dispatch: Claude Code gets `dispatch prime`
from a SessionStart hook in settings.json; ZCode has no user-level hooks file, only plugins.

The plugin is generated here (not shipped as files) so every Mac gets the right paths:
  ~/tasks/.dispatch/zcode-plugin/
    .zcode-plugin/plugin.json, .claude-plugin/plugin.json
    hooks/hooks.json   SessionStart -> hooks/prime.sh
    hooks/prime.sh     BEADS_ACTOR=zcode dispatch prime --hook-json
    skills/task-board  -> the task-board skill (pool copy, else the one bundled with the app)
and registered by adding its path to `plugins.dirs` in ~/.zcode/cli/config.json, which ZCode
loads as an enabled inline plugin (no marketplace, no zip)."""
import json, os, shutil, sys

import dispatch as D

PLUGIN_NAME = "dispatch"
HERE = os.path.dirname(os.path.abspath(__file__))


def zcode_home(home=None):
    return os.path.join(home or D.HOME, ".zcode")


def config_path(home=None):
    return os.path.join(zcode_home(home), "cli", "config.json")


def plugin_dir(dispatch_dir=None):
    return os.path.join(dispatch_dir or D.DISPATCH_DIR, "zcode-plugin")


def skill_source():
    """The task-board skill to expose: the pool copy (what Claude / Codex mount), else the copy
    bundled next to the CLI (app bundle: Resources/agent/skills; repo: agent/skills)."""
    for cand in (os.path.join(D.POOL, "task-board"),
                 os.path.join(HERE, "..", "agent", "skills", "task-board"),
                 os.path.join(HERE, "..", "..", "agent", "skills", "task-board")):
        if os.path.isfile(os.path.join(cand, "SKILL.md")):
            return os.path.realpath(cand)
    return ""


def version():
    try:
        return open(os.path.join(HERE, "VERSION")).read().strip() or "dev"
    except OSError:
        return "dev"


def manifest():
    return {
        "name": PLUGIN_NAME,
        "version": version(),
        "description": "Dispatch 中央任务板：会话开始时注入身份、当前项目的任务和知识库（dispatch prime），并带上 task-board 技能。",
        "description_i18n": {"en": "Dispatch task board: injects identity, this project's tasks and wiki at session start (dispatch prime), with the task-board skill.",
                             "zh-CN": "Dispatch 中央任务板：会话开始时注入身份、当前项目的任务和知识库（dispatch prime），并带上 task-board 技能。"},
        "author": {"name": "Dispatch"},
        "license": "MIT",
        "keywords": ["dispatch", "task-board", "prime"],
    }


def hooks_json():
    return {"hooks": {"SessionStart": [{"matcher": "startup|resume|clear|compact", "hooks": [
        {"type": "command", "command": "bash \"${CLAUDE_PLUGIN_ROOT}/hooks/prime.sh\"", "timeout": 25, "statusMessage": "Dispatch prime…"}]}]}}


def prime_sh(cli_path):
    # ~/.local/bin/dispatch is the usual entry (a symlink into the app bundle); the absolute CLI
    # path recorded at install time is the fallback when that symlink is missing.
    return f"""#!/bin/bash
# Generated by `dispatch zcode-plugin install` — ZCode's SessionStart hook.
# Runs Dispatch's session-start digest as the zcode actor; the JSON on stdout becomes context.
# Always zcode, whatever the launching shell exported (a terminal-started ZCode inherits its env).
export BEADS_ACTOR=zcode
export DISPATCH_ACTOR=zcode
export PATH="$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"
if [ -x "$HOME/.local/bin/dispatch" ]; then
  exec "$HOME/.local/bin/dispatch" prime --hook-json
fi
exec python3 {json.dumps(cli_path)} prime --hook-json
"""


def read_config(path):
    try:
        with open(path, encoding="utf-8") as f:
            d = json.load(f)
        return d if isinstance(d, dict) else {}
    except (OSError, ValueError):
        return {}


def write_config(path, cfg):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(cfg, f, ensure_ascii=False, indent=2)
        f.write("\n")
    os.replace(tmp, path)


def registered(cfg, root):
    dirs = ((cfg.get("plugins") or {}).get("dirs") or []) if isinstance(cfg.get("plugins"), dict) else []
    return any(os.path.realpath(os.path.expanduser(d)) == os.path.realpath(root) for d in dirs if isinstance(d, str))


def install(home=None, dispatch_dir=None, skill=None, cli_path=None):
    root = plugin_dir(dispatch_dir)
    skill = skill if skill is not None else skill_source()
    cli_path = cli_path or os.path.realpath(os.path.join(HERE, "dispatch.py"))
    for sub in (".zcode-plugin", ".claude-plugin", "hooks", "skills"):
        os.makedirs(os.path.join(root, sub), exist_ok=True)
    for sub in (".zcode-plugin", ".claude-plugin"):
        write_config(os.path.join(root, sub, "plugin.json"), manifest())
    write_config(os.path.join(root, "hooks", "hooks.json"), hooks_json())
    sh_path = os.path.join(root, "hooks", "prime.sh")
    with open(sh_path, "w", encoding="utf-8") as f:
        f.write(prime_sh(cli_path))
    os.chmod(sh_path, 0o755)
    link = os.path.join(root, "skills", "task-board")
    if skill:
        if os.path.islink(link) or os.path.isfile(link):
            os.unlink(link)
        elif os.path.isdir(link):
            shutil.rmtree(link)
        os.symlink(skill, link)
    cfg_path = config_path(home)
    cfg = read_config(cfg_path)
    plugins = cfg.get("plugins") if isinstance(cfg.get("plugins"), dict) else {}
    dirs = [d for d in (plugins.get("dirs") or []) if isinstance(d, str)]
    if not registered(cfg, root):
        dirs.append(root)
    plugins["dirs"] = dirs
    if plugins.get("enabled") is False:
        plugins["enabled"] = True
    cfg["plugins"] = plugins
    write_config(cfg_path, cfg)
    return status(home, dispatch_dir)


def remove(home=None, dispatch_dir=None):
    root = plugin_dir(dispatch_dir)
    if os.path.isdir(root):
        shutil.rmtree(root)
    cfg_path = config_path(home)
    cfg = read_config(cfg_path)
    if isinstance(cfg.get("plugins"), dict):
        dirs = cfg["plugins"].get("dirs") or []
        cfg["plugins"]["dirs"] = [d for d in dirs if not (isinstance(d, str) and os.path.realpath(os.path.expanduser(d)) == os.path.realpath(root))]
        write_config(cfg_path, cfg)
    return status(home, dispatch_dir)


def status(home=None, dispatch_dir=None):
    root = plugin_dir(dispatch_dir)
    cfg = read_config(config_path(home))
    link = os.path.join(root, "skills", "task-board")
    files = os.path.isfile(os.path.join(root, "hooks", "hooks.json")) and os.path.isfile(os.path.join(root, "hooks", "prime.sh"))
    return {"zcode_installed": os.path.isdir(zcode_home(home)), "dir": root, "files": files, "registered": registered(cfg, root),
            "skill": os.path.realpath(link) if os.path.islink(link) else "", "installed": files and registered(cfg, root), "config": config_path(home)}


def command(a):
    if a.op == "install":
        r = install()
    elif a.op == "remove":
        r = remove()
    else:
        r = status()
    if a.json:
        print(json.dumps(r, ensure_ascii=False))
        return
    home = D.HOME
    if a.op == "remove":
        print(f"已移除 ZCode 插件（{r['dir'].replace(home, '~')}），config.json 里的 plugins.dirs 已清掉")
        return
    if not r["zcode_installed"]:
        print("这台电脑没装 ZCode（没有 ~/.zcode）；插件文件" + ("已生成" if r["files"] else "未生成") + "，装了 ZCode 再跑一次 install。")
    state = "已安装" if r["installed"] else ("文件在、没注册" if r["files"] else "未安装")
    print(f"ZCode 插件 {state}：{r['dir'].replace(home, '~')}")
    print(f"  注册：{r['config'].replace(home, '~')} → plugins.dirs {'✓' if r['registered'] else '✗'}")
    print(f"  技能：task-board → {r['skill'].replace(home, '~') if r['skill'] else '（没找到 task-board 技能）'}")
    if r["installed"]:
        print("  下一段 ZCode 会话开始时会注入 dispatch prime（新建或重开会话生效；已开着的会话不变）。")
