import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react';
import type { Activity, Issue } from '../types';
import type { Api } from '../api';
import { UNGROUPED_PROJECT, conversationProject, sessionLifecycle } from '../activity';
import { linkedSessions, originSession, projectGroups, projectHome, sourceTasks } from '../projectModel';
import { isArchived, isStarred, rankProjects, type ProjectFlags } from '../projectFlags';
import { ago, projectColor, projectOf, statusLabel } from '../derive';
import { ConversationRows } from './Workspace';
import { Markdown } from './Markdown';
import { MediaContext, MediaProvider, type AttachmentData } from './Media';

// A research / review / design write-up found in the project's folders or registered by hand.
type Doc = { id: string; title: string; kind: string; path: string; url?: boolean; html?: boolean; size?: number; mtime?: number; ext?: string; dir?: string; source?: string };
const shortPath = (p: string) => p.replace(/^\/(?:Users|home)\/[^/]+/, '~').replace('/Library/Mobile Documents/com~apple~CloudDocs', '/iCloud').replace('/Library/Mobile Documents/iCloud~md~obsidian/Documents', '/Obsidian');
const openExternal = (url: string) => import('@tauri-apps/plugin-opener').then((o) => o.openUrl(url)).catch(() => { window.open(url, '_blank'); });

// Images referenced relatively inside a document are read through the CLI (it only serves files
// next to the document); the Markdown component then renders them like conversation pictures.
function DocMedia({ api, project, id, dir, children }: { api: Api; project: string; id: string; dir?: string; children: ReactNode }) {
  const read = useCallback((ref: string) => api.on('local', ['docs', 'read', project, id, '--asset', ref, '--json']).then((t) => { const d = JSON.parse(t.slice(Math.max(0, t.indexOf('{')))) as AttachmentData & { error?: string }; if (d.error) throw new Error(d.error); return d; }), [api, project, id]);
  const open = useCallback((ref: string) => { void api.openPath(/^\//.test(ref) ? ref : `${dir || ''}/${ref}`).catch(() => {}); }, [api, dir]);
  const value = useMemo(() => ({ read, open, thumb: () => undefined }), [read, open]);
  return <MediaContext.Provider value={value}>{children}</MediaContext.Provider>;
}

// The project's own short facts (FACTS.md in its folder: servers, logins, who to ask) and the keys tied to it.
// Agents read the file only on demand (`dispatch facts … -P <project>`); values of keys never show here.
type ProjectFactsDoc = { path: string; content: string; exists: boolean; legacy?: { heading: string; body: string }[] };
type ProjectKey = { name: string; note: string; masked: string; length: number; project?: string };
const FACTS_TEMPLATE = (name: string) => `# ${name} 常用信息\n\n> 只放这个项目才用的短事实，Agent 需要时 \`dispatch facts get -P ${name} <主题>\` 读。密码和 Key 不写这里，放「规则与资料 → 密钥与 API」并填项目名。\n\n## 服务器\n\n**示例服务**\n- 入口 / 登录方式 / 找谁开账号\n`;
export function ProjectFactsView({ name, doc, keys, draft, busy, err, onEdit, onChange, onCancel, onSave, onOpenPath, onCopy }: { name: string; doc: ProjectFactsDoc | null; keys: ProjectKey[] | null; draft: string | null; busy: boolean; err: string; onEdit: () => void; onChange: (t: string) => void; onCancel: () => void; onSave: () => void; onOpenPath: (p: string) => void; onCopy: (t: string) => void }) {
  const hasLegacy = !!doc?.legacy?.length;
  return <section className="project-facts" aria-label="项目常用信息">
    <div className="hub-tools"><b>常用信息</b><span className="chip">FACTS.md</span>{doc?.path && <code className="muted small doc-path" title={doc.path}>{shortPath(doc.path)}</code>}<span className="spacer" />
      {draft === null
        ? <>{doc?.exists && <button className="btn sm" onClick={() => onOpenPath(doc.path)}>在 Finder 打开</button>}<button className="btn sm" disabled={busy || !doc} onClick={onEdit}>{doc?.exists ? '编辑' : '建一份'}</button></>
        : <><button className="btn sm" disabled={busy} onClick={onCancel}>取消</button><button className="btn primary sm" disabled={busy} onClick={onSave}>{busy ? '保存中…' : '保存'}</button></>}</div>
    <p className="muted small">只属于这个项目的短事实：服务器入口、登录方式、找谁。Agent 不会每次注入，需要时才 <span className="mono">dispatch facts get -P {name} 主题</span> 读。</p>
    {err && <p className="err small" role="alert">{err}</p>}
    {draft !== null ? <textarea className="project-facts-editor" aria-label="编辑项目常用信息" value={draft} onChange={(e) => onChange(e.target.value)} spellCheck={false} />
      : doc === null ? <p className="empty">正在读…</p>
      : doc.content ? <div className="doc-reader"><Markdown src={doc.content} /></div>
      : <p className="empty">{doc.path ? '还没有 FACTS.md。' : '还不知道这个项目的目录（先在项目目录里开一次会话）。'}{hasLegacy && ' 全局 FACTS.md 里有这个项目的旧节，见下。'}</p>}
    {hasLegacy && draft === null && <details className="project-facts-legacy"><summary className="muted small">全局 FACTS.md 里的旧项目节 · {doc!.legacy!.length}（可搬进项目 FACTS.md）</summary>{doc!.legacy!.map((l) => <div key={l.heading}><h4>{l.heading}</h4><Markdown src={l.body} /></div>)}</details>}
    <div className="hub-tools project-keys-head"><b>密钥</b><span className="muted small">{keys ? `${keys.length} 个 · 只列名字和用途，值在「规则与资料 → 密钥与 API」` : '…'}</span></div>
    {keys && keys.length > 0 && <div className="project-keys">{keys.map((k) => <div className="hub-task project-key" key={k.name}><code className="mono">{k.name}</code><span className="muted small">{k.note || '（没写用途）'}</span><span className="spacer" /><button className="btn sm" title={`dispatch env get ${k.name}`} onClick={() => onCopy(`dispatch env get ${k.name}`)}>复制取用命令</button></div>)}</div>}
    {keys && keys.length === 0 && <p className="empty small">还没有登记到这个项目的密钥。在「规则与资料 → 密钥与 API」添加时项目填 <span className="mono">{name}</span>，或 <span className="mono">dispatch env set 名 值 -P {name}</span>。</p>}
  </section>;
}

export function ProjectFacts({ api, name, onDone }: { api: Api; name: string; onDone?: (m: string) => void }) {
  const [doc, setDoc] = useState<ProjectFactsDoc | null>(null); const [keys, setKeys] = useState<ProjectKey[] | null>(null);
  const [draft, setDraft] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [err, setErr] = useState('');
  const parse = <T,>(t: string, fallback: T): T => { try { const i = Math.min(...[t.indexOf('{'), t.indexOf('[')].filter((x) => x >= 0)); return JSON.parse(t.slice(i)); } catch { return fallback; } };
  const load = useCallback(async () => {
    setErr('');
    const [d, k] = await Promise.allSettled([api.on('local', ['facts', 'show', '-P', name, '--json']), api.on('local', ['env', 'list', '-P', name, '--json'])]);
    setDoc(d.status === 'fulfilled' ? parse<ProjectFactsDoc>(d.value, { path: '', content: '', exists: false }) : { path: '', content: '', exists: false });
    setKeys(k.status === 'fulfilled' ? parse<ProjectKey[]>(k.value, []) : []);
    if (d.status === 'rejected') setErr(String(d.reason));
  }, [api, name]);
  useEffect(() => { setDoc(null); setKeys(null); setDraft(null); void load(); }, [load]);
  const save = async () => { if (draft === null) return; setBusy(true); setErr(''); try { await api.on('local', ['facts', 'write', '-P', name], draft); setDraft(null); onDone?.('已保存 FACTS.md（在项目目录，记得 commit）'); await load(); } catch (e) { setErr(String(e)); } finally { setBusy(false); } };
  return <ProjectFactsView name={name} doc={doc} keys={keys} draft={draft} busy={busy} err={err} onEdit={() => setDraft(doc?.content || FACTS_TEMPLATE(name))} onChange={setDraft} onCancel={() => setDraft(null)} onSave={() => void save()} onOpenPath={(p) => void api.openPath(p).catch(() => {})} onCopy={(t) => void api.copy(t).then(() => onDone?.('已复制')).catch(() => {})} />;
}

export function ProjectDocs({ api, name, docs, onReload }: { api: Api; name: string; docs: Doc[] | null; onReload: () => void }) {
  const [opened, setOpened] = useState<{ doc: Doc; text: string; dir?: string } | null>(null);
  const [err, setErr] = useState(''); const [path, setPath] = useState(''); const [kind, setKind] = useState('调研'); const [busy, setBusy] = useState(false);
  useEffect(() => { setOpened(null); setErr(''); setPath(''); }, [name]);
  const parse = (t: string) => { const d = JSON.parse(t.slice(Math.max(0, t.indexOf('{')))) as { error?: string; [k: string]: unknown }; if (d.error) throw new Error(d.error); return d; };
  const open = async (doc: Doc) => {
    setErr('');
    if (doc.url) { void openExternal(doc.path); return; }
    if (doc.html || doc.ext === 'html' || doc.ext === 'htm') { await api.openPath(doc.path).catch((e) => setErr(String(e))); return; }
    try { const d = parse(await api.on('local', ['docs', 'read', name, doc.id, '--json'])); setOpened({ doc, text: String(d.text || ''), dir: d.dir as string | undefined }); } catch (e) { setErr(String(e)); }
  };
  const add = async () => { setBusy(true); setErr(''); try { parse(await api.on('local', ['docs', 'add', name, path.trim(), '--kind', kind, '--json'])); setPath(''); onReload(); } catch (e) { setErr(String(e)); } finally { setBusy(false); } };
  const remove = async (doc: Doc) => { setBusy(true); setErr(''); try { parse(await api.on('local', ['docs', 'rm', name, doc.id, '--json'])); onReload(); } catch (e) { setErr(String(e)); } finally { setBusy(false); } };
  const actions = (d: Doc) => <>{d.url ? <button className="btn sm" onClick={() => void openExternal(d.path)}>打开链接</button> : <><button className="btn sm" onClick={() => void api.openPath(d.path).catch(() => {})}>在 Finder 打开</button><button className="btn sm" onClick={() => void api.copy(d.path).catch(() => {})}>复制路径</button></>}{d.source === 'registered' && <button className="btn sm" disabled={busy} onClick={() => void remove(d)}>移除登记</button>}</>;
  if (opened) {
    const d = opened.doc;
    return <div className="doc-reader"><div className="hub-tools"><button className="btn sm" onClick={() => setOpened(null)}>‹ 文档列表</button><span className="chip">{d.kind}</span><b>{d.title}</b><code className="muted small doc-path" title={d.path}>{shortPath(d.path)}</code><span className="spacer" />{actions(d)}</div><DocMedia api={api} project={name} id={d.id} dir={opened.dir}><Markdown src={opened.text} /></DocMedia></div>;
  }
  return <div className="docs-tab">
    <form className="doc-add" onSubmit={(e) => { e.preventDefault(); void add(); }}><input aria-label="文档路径或 URL" placeholder="路径或 URL，例如 design/research-2026-09-09.md" value={path} onChange={(e) => setPath(e.target.value)} /><select aria-label="文档类型" value={kind} onChange={(e) => setKind(e.target.value)}>{['调研', '复审', '设计', '文档', '其他'].map((k) => <option key={k}>{k}</option>)}</select><button className="btn primary sm" disabled={busy || !path.trim()}>登记文档…</button></form>
    {err && <p className="err">{err}</p>}
    {docs === null ? <p className="empty">正在扫描这个项目的 design/、docs/、研究/…</p> : docs.length === 0 ? <p className="empty">还没有文档。调研、复审产出写到项目的 design/ 目录，或在这里登记一个路径 / URL。</p> : <div className="doc-list">{docs.map((d) => <div className="hub-task doc-row" key={d.id}><button className="link doc-title" onClick={() => void open(d)}>{d.title}</button><span className="chip">{d.kind}</span><span className="muted small">{d.mtime ? new Date(d.mtime * 1000).toLocaleDateString('zh-CN') : ''}{d.size ? ` · ${d.size >= 1048576 ? `${(d.size / 1048576).toFixed(1)} MB` : `${Math.max(1, Math.round(d.size / 1024))} KB`}` : ''}</span><code className="muted small doc-path" title={d.path}>{shortPath(d.path)}</code><span className="spacer" />{actions(d)}</div>)}</div>}
  </div>;
}

// One paragraph on the whole project — what it is, where it stands, what is next — written by the
// summary model from the sessions' summaries and the board. Refreshes itself once a day; the
// button forces it.
function ProjectSummary({api,name}:{api:Api;name:string}) {
  const [s,setS]=useState<{summary:string;at?:number;by?:string;sessions?:number;open?:number;closed?:number;cached?:boolean}|null>(null);
  const [busy,setBusy]=useState(false);const [err,setErr]=useState('');
  const run=async(force:boolean)=>{setBusy(true);setErr('');try{const t=await api.on('local',['project-summary',name,force?'--force':'--if-stale','--json']);const d=JSON.parse(t.slice(Math.max(0,t.indexOf('{'))));if(d.error)setErr(d.error);else setS(d);}catch(e){setErr(String(e));}finally{setBusy(false);}};
  useEffect(()=>{setS(null);void run(false);},[name]);  // eslint-disable-line react-hooks/exhaustive-deps
  return <div className="project-summary">
    {s?.summary?<p className="t">{s.summary}</p>:<p className="muted small">{busy?'正在读这个项目的会话和任务，写总结…':err||'还没有总结'}</p>}
    <div className="project-summary-foot"><button className="btn sm" disabled={busy} onClick={()=>void run(true)}>{busy?'总结中…':s?.summary?'✦ 重新总结':'✦ 总结这个项目'}</button>{s?.at?<span className="muted small">{new Date(s.at*1000).toLocaleString('zh-CN',{hour12:false,month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})} · {s.by} · 读了 {s.sessions} 段会话、{(s.open??0)+(s.closed??0)} 个任务</span>:null}{err&&s?.summary?<span className="err small">{err}</span>:null}</div>
  </div>;
}

export function TaskRelations({issue,rows,api,onSaved,onOpen}:{issue:Issue;rows:Activity[];api:Api;onSaved:()=>void;onOpen:(id:string)=>void}) {
  const [edit,setEdit]=useState(false),[origin,setOrigin]=useState(''),[participants,setParticipants]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const ids=linkedSessions(issue);
  const options=rows.filter((a,n,all)=>all.findIndex(x=>x.session_id===a.session_id)===n).sort((a,b)=>Number(conversationProject(b)===projectOf(issue))-Number(conversationProject(a)===projectOf(issue)));
  const missing=ids.filter(id=>!options.some(a=>a.session_id===id));
  const save=async()=>{setBusy(true);setError('');try{const add=[...new Set([...participants,origin].filter(Boolean))].map(id=>'session:'+id);if(origin)add.push('session-origin:'+origin);await api.labels(issue.id,add,(issue.labels||[]).filter(l=>l.startsWith('session:')||l.startsWith('session-origin:')).filter(l=>!add.includes(l)));setEdit(false);onSaved();}catch(e){setError(String(e));}finally{setBusy(false);}};
  return <div className="task-relations"><div className="task-links">{ids.length?ids.map(id=><button key={id} className="chip" onClick={()=>onOpen(id)}>{originSession(issue)===id?'发起':'参与'} · {rows.find(a=>a.session_id===id)?.title||id.slice(0,8)} ↗</button>):<span className="muted small">没记录（Agent 建任务时通常会自动记）</span>}<button className="link" onClick={()=>{setOrigin(originSession(issue));setParticipants(ids);setEdit(!edit);}}>指定是哪次会话</button></div>{edit&&<div className="relation-editor"><label>发起会话<select aria-label="发起会话" value={origin} onChange={e=>setOrigin(e.target.value)}><option value="">暂不指定</option>{options.map(a=><option key={a.session_id} value={a.session_id}>{conversationProject(a)} · {a.title}</option>)}{missing.map(id=><option key={id} value={id}>{id}（历史会话）</option>)}</select></label><details><summary>参与会话 · 可选多个</summary><div className="relation-options">{options.map(a=><label key={a.session_id}><input type="checkbox" checked={participants.includes(a.session_id)} onChange={e=>setParticipants(old=>e.target.checked?[...old,a.session_id]:old.filter(x=>x!==a.session_id))}/>{a.title}</label>)}</div></details><button className="btn primary sm" disabled={busy} onClick={()=>void save()}>保存</button><button className="btn sm" disabled={busy} onClick={()=>setEdit(false)}>取消</button>{error&&<p role="alert">{error}</p>}</div>}</div>;
}

function OutcomeEditor({project,rows,tasks,initial,api,onSaved,onCancel}:{project:string;rows:Activity[];tasks:Issue[];initial?:Issue;api:Api;onSaved:()=>void;onCancel:()=>void}){
  const [title,setTitle]=useState(initial?.title||''),[body,setBody]=useState(initial?.description||''),[taskIds,setTaskIds]=useState<string[]>(initial?sourceTasks(initial):[]),[sessionIds,setSessionIds]=useState<string[]>(initial?linkedSessions(initial):[]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[created,setCreated]=useState(initial?.id||'');
  const save=async()=>{setBusy(true);setError('');try{const linked=[...new Set([...sessionIds,...tasks.filter(i=>taskIds.includes(i.id)).flatMap(linkedSessions)])];const labels=['dispatch:outcome',...(project===UNGROUPED_PROJECT?[]:['project:'+project]),...taskIds.map(id=>'outcome-task:'+id),...linked.map(id=>'session:'+id)];let id=created;if(!id){const result=await api.create({title:title.trim(),description:body.trim(),issue_type:'task',priority:2,labels});id=result.id;setCreated(id);}else{await api.update(id,{title:title.trim(),description:body.trim()});await api.labels(id,labels,(initial?.labels||[]).filter(l=>(l.startsWith('outcome-task:')||l.startsWith('session:'))&&!labels.includes(l)));}await api.close(id,'已登记项目成果');onSaved();}catch(e){setError(String(e));}finally{setBusy(false);}};
  return <form className="outcome-editor" onSubmit={e=>{e.preventDefault();void save();}}><h3>{initial?'编辑成果':'登记成果'}</h3><label>成果名称<input aria-label="成果名称" required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)} placeholder="例如：Dispatch 新版 · 项目工作台"/></label><label>交付内容与查看入口<textarea aria-label="交付内容与查看入口" required rows={5} value={body} onChange={e=>setBody(e.target.value)} placeholder="写明交付了什么，附上文档、截图、版本或代码链接（支持 Markdown）"/></label><div className="outcome-sources"><details open><summary>来源任务 · 可选多个</summary><div className="relation-options">{tasks.map(i=><label key={i.id}><input type="checkbox" checked={taskIds.includes(i.id)} onChange={e=>setTaskIds(old=>e.target.checked?[...old,i.id]:old.filter(x=>x!==i.id))}/>{i.title}</label>)}</div></details><details><summary>补充来源会话 · 已选任务的会话会一并关联</summary><div className="relation-options">{rows.map(a=><label key={a.key}><input type="checkbox" checked={sessionIds.includes(a.session_id)} onChange={e=>setSessionIds(old=>e.target.checked?[...old,a.session_id]:old.filter(x=>x!==a.session_id))}/>{a.title}</label>)}</div></details></div>{error&&<p role="alert">保存失败：{error}</p>}<button className="btn primary" disabled={busy||!title.trim()||!body.trim()}>保存成果</button><button className="btn" type="button" disabled={busy} onClick={onCancel}>取消</button></form>;
}

type Props={onDiscuss?:(name:string)=>void;archiveDays:number;flags:ProjectFlags;onFlag:(name:string,change:{starred?:boolean;archived?:boolean})=>void;connectionError:boolean;unavailable:string[];rows:Activity[];tasks:Issue[];outcomes:Issue[];api:Api;me:string;selected:string|null;onProject:(name:string|null)=>void;onOpen:(id:string)=>void;onTask:(id:string)=>void;onRead:(a:Activity)=>Promise<void>;onSummarize?:(a:Activity)=>Promise<void>;onReload:()=>void;onNew:(a?:Activity)=>void;loaded:boolean};
export function ProjectHub({onDiscuss,archiveDays,flags,onFlag,connectionError,unavailable,rows,tasks,outcomes,api,me,selected,onProject,onOpen,onTask,onRead,onSummarize,onReload,onNew,loaded}:Props){
  const [tab,setTab]=useState(()=>{const t=new URLSearchParams(location.search).get('section')||'sessions';return ['sessions','tasks','outcomes','unassigned','folders','docs'].includes(t)?t:'sessions';}),[query,setQuery]=useState(''),[scheduled,setScheduled]=useState(false),[archived,setArchived]=useState(false),[editor,setEditor]=useState<Issue|null|false>(false),[showOther,setShowOther]=useState(false),[showArchived,setShowArchived]=useState(false),[docs,setDocs]=useState<Doc[]|null>(null);
  const loadDocs=useCallback(()=>{setDocs(null);if(!selected)return;void api.on('local',['docs',selected,'--json']).then(t=>{const d=JSON.parse(t.slice(Math.max(0,t.indexOf('{'))));setDocs(Array.isArray(d.docs)?d.docs as Doc[]:[]);}).catch(()=>setDocs([]));},[api,selected]);
  useEffect(()=>{loadDocs();},[loadDocs]);
  const groups=useMemo(()=>projectGroups(rows,tasks,outcomes),[rows,tasks,outcomes]);
  const primary=(p:typeof groups[number])=>p.items.length>0||p.results.length>0||p.sessions.some(a=>!!a.project_override);
  const ranked=useMemo(()=>rankProjects(groups,flags),[groups,flags]);
  const project=groups.find(p=>p.name===selected);
  const starBtn=(name:string)=><button className={`star${isStarred(flags,name)?' on':''}`} onClick={e=>{e.stopPropagation();onFlag(name,{starred:!isStarred(flags,name)});}} title={isStarred(flags,name)?'取消收藏':'收藏：置顶，近期重点关注'} aria-label={isStarred(flags,name)?`取消收藏 ${name}`:`收藏 ${name}`}>{isStarred(flags,name)?'★':'☆'}</button>;
  const open=(name:string)=>{setTab('sessions');setQuery('');setScheduled(false);onProject(name);};
  const taskRow=(i:Issue)=><div className="hub-task" key={i.id}><button className="link task-title" onClick={()=>onTask(i.id)}>{i.title}</button><span className="st sm">{statusLabel(i).text}</span><TaskRelations issue={i} rows={rows} api={api} onSaved={onReload} onOpen={onOpen}/></div>;
  if(!project)return <div className="project-hub"><header className="hub-heading"><div><h2>从项目继续工作</h2><p>项目 → 会话 → 任务 → 成果</p><span className="muted small">{connectionError?"更新中断，正在重新连接":loaded?"每 3 秒同步会话活动":"正在连接…"}</span></div><div className="hub-header-actions"><button className="btn primary" onClick={()=>onNew()}>新建会话</button></div></header>{unavailable.length>0&&<p className="connection-note">{unavailable.join("、")} 暂时无法连接，保留已读取记录。</p>}<label className="search"><input placeholder="搜索项目…" value={query} onChange={e=>setQuery(e.target.value)}/></label>{!loaded&&<p className="empty">正在读取项目与会话…</p>}{(()=>{const list=(showArchived?ranked.archived:ranked.active).filter(p=>(showArchived||showOther||query.trim()||primary(p))&&p.name.toLowerCase().includes(query.toLowerCase()));const WEEK=7*86400,now=Date.now()/1000;const info=(p:typeof list[number])=>{const active=p.sessions.filter(a=>!a.scheduled&&sessionLifecycle(a,archiveDays)!=='archived');const unread=active.filter(a=>a.unread).length;const doing=p.items.find(i=>i.status==='in_progress');const openCount=p.items.filter(i=>i.status!=='closed').length;const live=unread>0||!!doing||active.some(a=>a.state==='working'&&!a.stale)||(p.last>0&&now-p.last<WEEK);
    // One line that says what the project is up to, never a raw chat reply.
    const blurb=doing?`进行中 · ${doing.title}`:p.results[0]?`最新成果 · ${p.results[0].title}`:active[0]?`最近会话 · ${active[0].title}`:'还没有会话或任务';return{active,unread,openCount,live,blurb};};const cards=list.filter(p=>info(p).live),quiet=list.filter(p=>!info(p).live);return <><div className="project-cards">{cards.map(p=>{const x=info(p);return <div className="project-card" data-project={p.name} role="button" tabIndex={0} key={p.name} onClick={()=>open(p.name)} onKeyDown={e=>{if(e.target===e.currentTarget&&e.key==='Enter')open(p.name);}} title="右键：收藏、归档、新建会话"><div><h3>{p.name}</h3>{starBtn(p.name)}{x.unread>0&&<span className="activity-badge new">{x.unread} 个会话未读</span>}</div><p>{x.blurb}</p><div className="muted small">{x.active.length} 个会话 · {x.openCount} 个待完成任务 · {p.results.length} 项成果</div><div className="project-card-foot"><span className="link">{primary(p)?"进入项目 →":"查看目录会话 →"}</span><span className="muted small">{p.last?`${ago(p.last)}`:''}</span></div></div>;})}</div>{quiet.length>0&&<div className="project-quiet"><h4 className="muted small">最近没有动静 · {quiet.length}</h4>{quiet.map(p=>{const x=info(p);return <div className="home-rest-item opens" data-project={p.name} role="button" tabIndex={0} key={p.name} onClick={()=>open(p.name)} onKeyDown={e=>{if(e.key==='Enter')open(p.name);}} title="右键：收藏、归档、新建会话"><span className="proj" style={{background:projectColor(p.name)}}/><b>{p.name}</b>{starBtn(p.name)}<span className="muted small">{x.active.length} 个会话 · {x.openCount} 项未完成{p.results.length?` · ${p.results.length} 项成果`:''}</span><span className="muted small right">{p.last?`${ago(p.last)}`:''}</span></div>;})}</div>}</>;})()}{showArchived&&ranked.archived.length===0&&<p className="empty">没有归档的项目。</p>}<div className="hub-list-foot"><button className="btn" onClick={()=>{setShowOther(!showOther);setShowArchived(false);}}>{showOther&&!showArchived?"收起其他目录":`其他目录与未归类 · ${ranked.active.filter(p=>!primary(p)).length}`}</button><button className={`btn${showArchived?' on':''}`} onClick={()=>setShowArchived(!showArchived)}>{showArchived?"返回项目列表":`已归档 · ${ranked.archived.length}`}</button></div></div>;
  const life=(a:Activity)=>sessionLifecycle(a,archiveDays);
  const archivedCount=project.sessions.filter(a=>!a.scheduled&&life(a)==='archived').length;
  const visible=project.sessions.filter(a=>scheduled?!!a.scheduled:!a.scheduled&&(archived?life(a)==='archived':life(a)!=='archived')).sort((x,y)=>Number(!!y.starred)-Number(!!x.starred)||y.last_at-x.last_at).filter(a=>`${a.title} ${a.cwd} ${a.overview||''}`.toLowerCase().includes(query.toLowerCase()));
  const unassigned=project.items.filter(i=>!linkedSessions(i).length);
  const short=shortPath;
  const dirs=[...project.sessions.reduce((m,a)=>{const d=(a.cwd||'').replace(/\/+$/,'');if(!d)return m;const cur=m.get(d)||{count:0,last:0,latest:a};cur.count++;if(a.last_at>cur.last){cur.last=a.last_at;cur.latest=a;}return m.set(d,cur);},new Map<string,{count:number;last:number;latest:Activity}>())].sort((x,y)=>y[1].last-x[1].last);
  return <div className="project-hub"><button className="link" onClick={()=>{setQuery('');onProject(null);}}>‹ 全部项目</button><header className="hub-heading"><div><h2>{project.name}{starBtn(project.name)}{isArchived(flags,project.name)&&<span className="st sm open">已归档</span>}</h2><p>{project.sessions.filter(a=>!a.scheduled).length} 个会话 · {project.items.length} 个任务 · {project.results.length} 项成果</p><ProjectSummary api={api} name={project.name}/></div><div className="hub-header-actions">{onDiscuss&&<button className="btn" onClick={()=>onDiscuss(project.name)} title="就这个项目的一个想法，让几个 Agent 各说一次并出结论">讨论…</button>}<button className="btn primary" onClick={()=>onNew(projectHome(project.sessions))}>在此项目新建会话</button><button className="btn" onClick={()=>onFlag(project.name,{archived:!isArchived(flags,project.name)})} title={isArchived(flags,project.name)?'恢复到工作台和项目列表':'做完了、暂时不用：从工作台和项目列表隐藏，随时可找回'}>{isArchived(flags,project.name)?'取消归档':'归档'}</button></div></header><div className="hub-tabs views">{[['sessions','会话',project.sessions.filter(a=>!a.scheduled).length],['tasks','任务',project.items.length],['outcomes','成果',project.results.length],['unassigned','待归属任务',unassigned.length],['folders','目录',dirs.length],['docs','文档',docs?docs.length:'…']].map(([id,label,n])=><button className={tab===id?'on':''} key={id} onClick={()=>{setTab(String(id));setEditor(false);}}>{label} {n}</button>)}</div>
  {tab==='sessions'&&<><div className="hub-tools"><input aria-label="搜索项目会话" placeholder="搜索这个项目的会话…" value={query} onChange={e=>setQuery(e.target.value)}/><button className={`btn sm${archived?' on':''}`} onClick={()=>{setArchived(!archived);setScheduled(false);}} title={`手动归档，或超过 ${archiveDays} 天没有活动`}>{archived?'返回最近会话':`已归档 ${archivedCount}`}</button><button className="btn sm" onClick={()=>{setScheduled(!scheduled);setArchived(false);}}>{scheduled?'返回普通会话':`定时会话 ${project.sessions.filter(a=>a.scheduled).length}`}</button></div><ConversationRows rows={visible} me={me} onOpen={onOpen} onRead={onRead} onSummarize={onSummarize} taskContent={a=>{const linked=project.items.filter(i=>linkedSessions(i).includes(a.session_id));return <details className="conversation-tasks"><summary>会话任务 · {linked.length} 项{linked.length?` · ${linked.filter(i=>i.status==='closed').length} 已完成`:''}</summary>{linked.length?linked.map(taskRow):<p className="muted small">没有明确关联的任务。可在“待归属任务”中指定；聊天里的提及不自动算作归属。</p>}</details>;}}/>{visible.length===0&&<p className="empty">{archived?'没有归档的会话。':'这个分类没有会话。'}</p>}</>}
  {(tab==='tasks'||tab==='unassigned')&&<><p className="muted">任务显示发起和参与会话；历史任务没有明确关系时保留待归属，不根据提及次数猜测。</p>{(tab==='unassigned'?unassigned:project.items).map(taskRow)}{tab==='unassigned'&&!unassigned.length&&<p className="empty">任务都已有明确关联。</p>}</>}
  {tab==='folders'&&<><p className="muted">这个项目的会话在哪些文件夹里发生过。</p>{dirs.map(([d,info])=><div className="hub-task hub-dir" key={d}><div className="hub-dir-head"><code title={d}>{short(d)}</code><span className="muted small">{info.count} 个会话 · 最近 {ago(info.last)}</span></div><div className="task-links"><button className="btn sm" onClick={()=>onNew(info.latest)}>在此目录新建会话</button><button className="btn sm" onClick={()=>api.openPath(d).catch(()=>{})}>在 Finder 打开</button><button className="btn sm" onClick={()=>api.copy(`cd '${d}'`).catch(()=>{})}>复制 cd</button></div></div>)}{!dirs.length&&<p className="empty">没有记录到工作目录。</p>}</>}
  {tab==='docs'&&<><ProjectFacts api={api} name={project.name}/><ProjectDocs api={api} name={project.name} docs={docs} onReload={loadDocs}/></>}
  {tab==='outcomes'&&<>{editor!==false?<OutcomeEditor key={editor?.id||"new"} project={project.name} rows={project.sessions} tasks={project.items} initial={editor||undefined} api={api} onCancel={()=>setEditor(false)} onSaved={()=>{setEditor(false);onReload();}}/>:<button className="btn primary" onClick={()=>setEditor(null)}>登记成果</button>}{project.results.map(r=><article className="outcome-card" key={r.id}><div className="hub-heading"><h3>{r.title}</h3><button className="btn sm" onClick={()=>setEditor(r)}>编辑</button></div><MediaProvider api={api} session={rows.find(a=>linkedSessions(r).includes(a.session_id))}><Markdown src={r.description||''}/></MediaProvider><div className="task-links">{sourceTasks(r).map(id=><button key={id} className="chip" onClick={()=>onTask(id)}>任务 · {tasks.find(i=>i.id===id)?.title||id}</button>)}{linkedSessions(r).map(id=><button key={id} className="chip" onClick={()=>onOpen(id)}>会话 · {rows.find(a=>a.session_id===id)?.title||id.slice(0,8)} ↗</button>)}</div></article>)}{!project.results.length&&editor===false&&<p className="empty">还没有登记成果。可以把多个任务、多个会话的交付汇总在这里。</p>}<details className="hub-history"><summary>历史完成记录 · {project.items.filter(i=>i.status==='closed').length} 项</summary><p className="muted small">这些是任务完成说明，尚未整理为独立成果。</p>{project.items.filter(i=>i.status==='closed').map(i=><div className="hub-task" key={i.id}><button className="link" onClick={()=>onTask(i.id)}>{i.title}</button><p>{i.close_reason||'打开任务查看完成说明'}</p></div>)}</details></>}
  </div>;
}
