import { useMemo, useState } from 'react';
import type { Activity, Issue } from '../types';
import type { Api } from '../api';
import { UNGROUPED_PROJECT, conversationProject, sessionLifecycle } from '../activity';
import { linkedSessions, originSession, projectGroups, sourceTasks } from '../projectModel';
import { isArchived, isStarred, rankProjects, type ProjectFlags } from '../projectFlags';
import { durSince, projectColor, projectOf, statusLabel } from '../derive';
import { ConversationRows } from './Workspace';
import { Markdown } from './Markdown';
import { MediaProvider } from './Media';

export function TaskRelations({issue,rows,api,onSaved,onOpen}:{issue:Issue;rows:Activity[];api:Api;onSaved:()=>void;onOpen:(id:string)=>void}) {
  const [edit,setEdit]=useState(false),[origin,setOrigin]=useState(''),[participants,setParticipants]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const ids=linkedSessions(issue);
  const options=rows.filter((a,n,all)=>all.findIndex(x=>x.session_id===a.session_id)===n).sort((a,b)=>Number(conversationProject(b)===projectOf(issue))-Number(conversationProject(a)===projectOf(issue)));
  const missing=ids.filter(id=>!options.some(a=>a.session_id===id));
  const save=async()=>{setBusy(true);setError('');try{const add=[...new Set([...participants,origin].filter(Boolean))].map(id=>'session:'+id);if(origin)add.push('session-origin:'+origin);await api.labels(issue.id,add,(issue.labels||[]).filter(l=>l.startsWith('session:')||l.startsWith('session-origin:')).filter(l=>!add.includes(l)));setEdit(false);onSaved();}catch(e){setError(String(e));}finally{setBusy(false);}};
  return <div className="task-relations"><div className="task-links">{ids.length?ids.map(id=><button key={id} className="chip" onClick={()=>onOpen(id)}>{originSession(issue)===id?'发起':'参与'} · {rows.find(a=>a.session_id===id)?.title||id.slice(0,8)} ↗</button>):<span className="muted small">还不知道这个任务是哪次会话建的</span>}<button className="link" onClick={()=>{setOrigin(originSession(issue));setParticipants(ids);setEdit(!edit);}}>指定是哪次会话</button></div>{edit&&<div className="relation-editor"><label>发起会话<select aria-label="发起会话" value={origin} onChange={e=>setOrigin(e.target.value)}><option value="">暂不指定</option>{options.map(a=><option key={a.session_id} value={a.session_id}>{conversationProject(a)} · {a.title}</option>)}{missing.map(id=><option key={id} value={id}>{id}（历史会话）</option>)}</select></label><details><summary>参与会话 · 可选多个</summary><div className="relation-options">{options.map(a=><label key={a.session_id}><input type="checkbox" checked={participants.includes(a.session_id)} onChange={e=>setParticipants(old=>e.target.checked?[...old,a.session_id]:old.filter(x=>x!==a.session_id))}/>{a.title}</label>)}</div></details><button className="btn primary sm" disabled={busy} onClick={()=>void save()}>保存</button><button className="btn sm" disabled={busy} onClick={()=>setEdit(false)}>取消</button>{error&&<p role="alert">{error}</p>}</div>}</div>;
}

function OutcomeEditor({project,rows,tasks,initial,api,onSaved,onCancel}:{project:string;rows:Activity[];tasks:Issue[];initial?:Issue;api:Api;onSaved:()=>void;onCancel:()=>void}){
  const [title,setTitle]=useState(initial?.title||''),[body,setBody]=useState(initial?.description||''),[taskIds,setTaskIds]=useState<string[]>(initial?sourceTasks(initial):[]),[sessionIds,setSessionIds]=useState<string[]>(initial?linkedSessions(initial):[]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[created,setCreated]=useState(initial?.id||'');
  const save=async()=>{setBusy(true);setError('');try{const linked=[...new Set([...sessionIds,...tasks.filter(i=>taskIds.includes(i.id)).flatMap(linkedSessions)])];const labels=['dispatch:outcome',...(project===UNGROUPED_PROJECT?[]:['project:'+project]),...taskIds.map(id=>'outcome-task:'+id),...linked.map(id=>'session:'+id)];let id=created;if(!id){const result=await api.create({title:title.trim(),description:body.trim(),issue_type:'task',priority:2,labels});id=result.id;setCreated(id);}else{await api.update(id,{title:title.trim(),description:body.trim()});await api.labels(id,labels,(initial?.labels||[]).filter(l=>(l.startsWith('outcome-task:')||l.startsWith('session:'))&&!labels.includes(l)));}await api.close(id,'已登记项目成果');onSaved();}catch(e){setError(String(e));}finally{setBusy(false);}};
  return <form className="outcome-editor" onSubmit={e=>{e.preventDefault();void save();}}><h3>{initial?'编辑成果':'登记成果'}</h3><label>成果名称<input aria-label="成果名称" required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)} placeholder="例如：Dispatch 新版 · 项目工作台"/></label><label>交付内容与查看入口<textarea aria-label="交付内容与查看入口" required rows={5} value={body} onChange={e=>setBody(e.target.value)} placeholder="写明交付了什么，附上文档、截图、版本或代码链接（支持 Markdown）"/></label><div className="outcome-sources"><details open><summary>来源任务 · 可选多个</summary><div className="relation-options">{tasks.map(i=><label key={i.id}><input type="checkbox" checked={taskIds.includes(i.id)} onChange={e=>setTaskIds(old=>e.target.checked?[...old,i.id]:old.filter(x=>x!==i.id))}/>{i.title}</label>)}</div></details><details><summary>补充来源会话 · 已选任务的会话会一并关联</summary><div className="relation-options">{rows.map(a=><label key={a.key}><input type="checkbox" checked={sessionIds.includes(a.session_id)} onChange={e=>setSessionIds(old=>e.target.checked?[...old,a.session_id]:old.filter(x=>x!==a.session_id))}/>{a.title}</label>)}</div></details></div>{error&&<p role="alert">保存失败：{error}</p>}<button className="btn primary" disabled={busy||!title.trim()||!body.trim()}>保存成果</button><button className="btn" type="button" disabled={busy} onClick={onCancel}>取消</button></form>;
}

type Props={archiveDays:number;flags:ProjectFlags;onFlag:(name:string,change:{starred?:boolean;archived?:boolean})=>void;connectionError:boolean;unavailable:string[];rows:Activity[];tasks:Issue[];outcomes:Issue[];api:Api;me:string;selected:string|null;onProject:(name:string|null)=>void;onOpen:(id:string)=>void;onTask:(id:string)=>void;onRead:(a:Activity)=>Promise<void>;onReload:()=>void;onNew:(a?:Activity)=>void;loaded:boolean};
export function ProjectHub({archiveDays,flags,onFlag,connectionError,unavailable,rows,tasks,outcomes,api,me,selected,onProject,onOpen,onTask,onRead,onReload,onNew,loaded}:Props){
  const [tab,setTab]=useState(()=>{const t=new URLSearchParams(location.search).get('section')||'sessions';return ['sessions','tasks','outcomes','unassigned','folders'].includes(t)?t:'sessions';}),[query,setQuery]=useState(''),[scheduled,setScheduled]=useState(false),[archived,setArchived]=useState(false),[editor,setEditor]=useState<Issue|null|false>(false),[showOther,setShowOther]=useState(false),[showArchived,setShowArchived]=useState(false);
  const groups=useMemo(()=>projectGroups(rows,tasks,outcomes),[rows,tasks,outcomes]);
  const primary=(p:typeof groups[number])=>p.items.length>0||p.results.length>0||p.sessions.some(a=>!!a.project_override);
  const ranked=useMemo(()=>rankProjects(groups,flags),[groups,flags]);
  const project=groups.find(p=>p.name===selected);
  const starBtn=(name:string)=><button className={`star${isStarred(flags,name)?' on':''}`} onClick={e=>{e.stopPropagation();onFlag(name,{starred:!isStarred(flags,name)});}} title={isStarred(flags,name)?'取消收藏':'收藏：置顶，近期重点关注'} aria-label={isStarred(flags,name)?`取消收藏 ${name}`:`收藏 ${name}`}>{isStarred(flags,name)?'★':'☆'}</button>;
  const open=(name:string)=>{setTab('sessions');setQuery('');setScheduled(false);onProject(name);};
  const taskRow=(i:Issue)=><div className="hub-task" key={i.id}><button className="link task-title" onClick={()=>onTask(i.id)}>{i.title}</button><span className="st sm">{statusLabel(i).text}</span><TaskRelations issue={i} rows={rows} api={api} onSaved={onReload} onOpen={onOpen}/></div>;
  if(!project)return <div className="project-hub"><header className="hub-heading"><div><h2>从项目继续工作</h2><p>项目 → 会话 → 任务 → 成果</p><span className="muted small">{connectionError?"更新中断，正在重新连接":loaded?"每 3 秒同步会话活动":"正在连接…"}</span></div><div className="hub-header-actions"><button className="btn primary" onClick={()=>onNew()}>新建会话</button></div></header>{unavailable.length>0&&<p className="connection-note">{unavailable.join("、")} 暂时无法连接，保留已读取记录。</p>}<label className="search"><input placeholder="搜索项目…" value={query} onChange={e=>setQuery(e.target.value)}/></label>{!loaded&&<p className="empty">正在读取项目与会话…</p>}{(()=>{const list=(showArchived?ranked.archived:ranked.active).filter(p=>(showArchived||showOther||query.trim()||primary(p))&&p.name.toLowerCase().includes(query.toLowerCase()));const WEEK=7*86400,now=Date.now()/1000;const info=(p:typeof list[number])=>{const active=p.sessions.filter(a=>!a.scheduled&&sessionLifecycle(a,archiveDays)!=='archived');const unread=active.filter(a=>a.unread).length;const doing=p.items.find(i=>i.status==='in_progress');const openCount=p.items.filter(i=>i.status!=='closed').length;const live=unread>0||!!doing||active.some(a=>a.state==='working'&&!a.stale)||(p.last>0&&now-p.last<WEEK);
    // One line that says what the project is up to, never a raw chat reply.
    const blurb=doing?`进行中 · ${doing.title}`:p.results[0]?`最新成果 · ${p.results[0].title}`:active[0]?`最近会话 · ${active[0].title}`:'还没有会话或任务';return{active,unread,openCount,live,blurb};};const cards=list.filter(p=>info(p).live),quiet=list.filter(p=>!info(p).live);return <><div className="project-cards">{cards.map(p=>{const x=info(p);return <div className="project-card" data-project={p.name} role="button" tabIndex={0} key={p.name} onClick={()=>open(p.name)} onKeyDown={e=>{if(e.target===e.currentTarget&&e.key==='Enter')open(p.name);}} title="右键：收藏、归档、新建会话"><div><h3>{p.name}</h3>{starBtn(p.name)}{x.unread>0&&<span className="activity-badge new">{x.unread} 个会话未读</span>}</div><p>{x.blurb}</p><div className="muted small">{x.active.length} 个会话 · {x.openCount} 个待完成任务 · {p.results.length} 项成果</div><div className="project-card-foot"><span className="link">{primary(p)?"进入项目 →":"查看目录会话 →"}</span><span className="muted small">{p.last?`${durSince(p.last)}前`:''}</span></div></div>;})}</div>{quiet.length>0&&<div className="project-quiet"><h4 className="muted small">最近没有动静 · {quiet.length}</h4>{quiet.map(p=>{const x=info(p);return <div className="home-rest-item opens" data-project={p.name} role="button" tabIndex={0} key={p.name} onClick={()=>open(p.name)} onKeyDown={e=>{if(e.key==='Enter')open(p.name);}} title="右键：收藏、归档、新建会话"><span className="proj" style={{background:projectColor(p.name)}}/><b>{p.name}</b>{starBtn(p.name)}<span className="muted small">{x.active.length} 个会话 · {x.openCount} 项未完成{p.results.length?` · ${p.results.length} 项成果`:''}</span><span className="muted small right">{p.last?`${durSince(p.last)}前`:''}</span></div>;})}</div>}</>;})()}{showArchived&&ranked.archived.length===0&&<p className="empty">没有归档的项目。</p>}<div className="hub-list-foot"><button className="btn" onClick={()=>{setShowOther(!showOther);setShowArchived(false);}}>{showOther&&!showArchived?"收起其他目录":`其他目录与未归类 · ${ranked.active.filter(p=>!primary(p)).length}`}</button><button className={`btn${showArchived?' on':''}`} onClick={()=>setShowArchived(!showArchived)}>{showArchived?"返回项目列表":`已归档 · ${ranked.archived.length}`}</button></div></div>;
  const life=(a:Activity)=>sessionLifecycle(a,archiveDays);
  const archivedCount=project.sessions.filter(a=>!a.scheduled&&life(a)==='archived').length;
  const visible=project.sessions.filter(a=>scheduled?!!a.scheduled:!a.scheduled&&(archived?life(a)==='archived':life(a)!=='archived')).sort((x,y)=>Number(!!y.starred)-Number(!!x.starred)||y.last_at-x.last_at).filter(a=>`${a.title} ${a.cwd} ${a.overview||''}`.toLowerCase().includes(query.toLowerCase()));
  const unassigned=project.items.filter(i=>!linkedSessions(i).length);
  const short=(p:string)=>p.replace(/^\/(?:Users|home)\/[^/]+/,'~').replace('/Library/Mobile Documents/com~apple~CloudDocs','/iCloud').replace('/Library/Mobile Documents/iCloud~md~obsidian/Documents','/Obsidian');
  const dirs=[...project.sessions.reduce((m,a)=>{const d=(a.cwd||'').replace(/\/+$/,'');if(!d)return m;const cur=m.get(d)||{count:0,last:0,latest:a};cur.count++;if(a.last_at>cur.last){cur.last=a.last_at;cur.latest=a;}return m.set(d,cur);},new Map<string,{count:number;last:number;latest:Activity}>())].sort((x,y)=>y[1].last-x[1].last);
  return <div className="project-hub"><button className="link" onClick={()=>{setQuery('');onProject(null);}}>‹ 全部项目</button><header className="hub-heading"><div><h2>{project.name}{starBtn(project.name)}{isArchived(flags,project.name)&&<span className="st sm open">已归档</span>}</h2><p>{project.sessions.filter(a=>!a.scheduled).length} 个会话 · {project.items.length} 个任务 · {project.results.length} 项成果</p></div><div className="hub-header-actions"><button className="btn primary" onClick={()=>onNew(project.sessions[0])}>在此项目新建会话</button><button className="btn" onClick={()=>onFlag(project.name,{archived:!isArchived(flags,project.name)})} title={isArchived(flags,project.name)?'恢复到工作台和项目列表':'做完了、暂时不用：从工作台和项目列表隐藏，随时可找回'}>{isArchived(flags,project.name)?'取消归档':'归档'}</button></div></header><div className="hub-tabs views">{[['sessions','会话',project.sessions.filter(a=>!a.scheduled).length],['tasks','任务',project.items.length],['outcomes','成果',project.results.length],['unassigned','待归属任务',unassigned.length],['folders','目录',dirs.length]].map(([id,label,n])=><button className={tab===id?'on':''} key={id} onClick={()=>{setTab(String(id));setEditor(false);}}>{label} {n}</button>)}</div>
  {tab==='sessions'&&<><div className="hub-tools"><input aria-label="搜索项目会话" placeholder="搜索这个项目的会话…" value={query} onChange={e=>setQuery(e.target.value)}/><button className={`btn sm${archived?' on':''}`} onClick={()=>{setArchived(!archived);setScheduled(false);}} title={`手动归档，或超过 ${archiveDays} 天没有活动`}>{archived?'返回最近会话':`已归档 ${archivedCount}`}</button><button className="btn sm" onClick={()=>{setScheduled(!scheduled);setArchived(false);}}>{scheduled?'返回普通会话':`定时会话 ${project.sessions.filter(a=>a.scheduled).length}`}</button></div><ConversationRows rows={visible} me={me} onOpen={onOpen} onRead={onRead} taskContent={a=>{const linked=project.items.filter(i=>linkedSessions(i).includes(a.session_id));return <details className="conversation-tasks"><summary>会话任务 · {linked.length} 项{linked.length?` · ${linked.filter(i=>i.status==='closed').length} 已完成`:''}</summary>{linked.length?linked.map(taskRow):<p className="muted small">没有明确关联的任务。可在“待归属任务”中指定；聊天里的提及不自动算作归属。</p>}</details>;}}/>{visible.length===0&&<p className="empty">{archived?'没有归档的会话。':'这个分类没有会话。'}</p>}</>}
  {(tab==='tasks'||tab==='unassigned')&&<><p className="muted">任务显示发起和参与会话；历史任务没有明确关系时保留待归属，不根据提及次数猜测。</p>{(tab==='unassigned'?unassigned:project.items).map(taskRow)}{tab==='unassigned'&&!unassigned.length&&<p className="empty">任务都已有明确关联。</p>}</>}
  {tab==='folders'&&<><p className="muted">这个项目的会话在哪些文件夹里发生过。</p>{dirs.map(([d,info])=><div className="hub-task hub-dir" key={d}><div className="hub-dir-head"><code title={d}>{short(d)}</code><span className="muted small">{info.count} 个会话 · 最近 {durSince(info.last)}前</span></div><div className="task-links"><button className="btn sm" onClick={()=>onNew(info.latest)}>在此目录新建会话</button><button className="btn sm" onClick={()=>api.openPath(d).catch(()=>{})}>在 Finder 打开</button><button className="btn sm" onClick={()=>api.copy(`cd '${d}'`).catch(()=>{})}>复制 cd</button></div></div>)}{!dirs.length&&<p className="empty">没有记录到工作目录。</p>}</>}
  {tab==='outcomes'&&<>{editor!==false?<OutcomeEditor key={editor?.id||"new"} project={project.name} rows={project.sessions} tasks={project.items} initial={editor||undefined} api={api} onCancel={()=>setEditor(false)} onSaved={()=>{setEditor(false);onReload();}}/>:<button className="btn primary" onClick={()=>setEditor(null)}>登记成果</button>}{project.results.map(r=><article className="outcome-card" key={r.id}><div className="hub-heading"><h3>{r.title}</h3><button className="btn sm" onClick={()=>setEditor(r)}>编辑</button></div><MediaProvider api={api} session={rows.find(a=>linkedSessions(r).includes(a.session_id))}><Markdown src={r.description||''}/></MediaProvider><div className="task-links">{sourceTasks(r).map(id=><button key={id} className="chip" onClick={()=>onTask(id)}>任务 · {tasks.find(i=>i.id===id)?.title||id}</button>)}{linkedSessions(r).map(id=><button key={id} className="chip" onClick={()=>onOpen(id)}>会话 · {rows.find(a=>a.session_id===id)?.title||id.slice(0,8)} ↗</button>)}</div></article>)}{!project.results.length&&editor===false&&<p className="empty">还没有登记成果。可以把多个任务、多个会话的交付汇总在这里。</p>}<details className="hub-history"><summary>历史完成记录 · {project.items.filter(i=>i.status==='closed').length} 项</summary><p className="muted small">这些是任务完成说明，尚未整理为独立成果。</p>{project.items.filter(i=>i.status==='closed').map(i=><div className="hub-task" key={i.id}><button className="link" onClick={()=>onTask(i.id)}>{i.title}</button><p>{i.close_reason||'打开任务查看完成说明'}</p></div>)}</details></>}
  </div>;
}
